package st.finanse.mod.finance;

import st.finanse.UpdateI;
import st.finanse.gui.Frame;
import st.finanse.proj.Project;

/**
 *
 * @author ShookTea
 */
public class AllFinance extends javax.swing.JInternalFrame implements UpdateI {

    /** Creates new form AllFinance */
    public AllFinance() {
        initComponents();
        Project.project.createFinanceModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createNewMonth = new javax.swing.JButton();
        showSum = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Wszystkie tabele");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Project.project.createFinanceModel(),
            new String [] {
                "Rok", "Miesiąc", "Zamknięty?", "Pokaż"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        createNewMonth.setText("Stwórz nowy miesiąc");
        createNewMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewMonthActionPerformed(evt);
            }
        });

        showSum.setText("Podsumowanie");
        showSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showSum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewMonth)
                    .addComponent(showSum))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.rowAtPoint(evt.getPoint());
        int c = jTable1.columnAtPoint(evt.getPoint());
        if (c == 3) { //Pokazuj tabelę
            Frame.addJIF(new FinanceTab(Project.project.getFinance(r)));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void createNewMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewMonthActionPerformed
        Frame.addJIF(new NewFinance());
    }//GEN-LAST:event_createNewMonthActionPerformed

    private void showSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSumActionPerformed
        Frame.addJIF(new FinanceSum());
    }//GEN-LAST:event_showSumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewMonth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showSum;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateData() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Project.project.createFinanceModel(),
            new String [] {
                "Rok", "Miesiąc", "Zamknięty?", "Pokaż"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

}
