package st.finanse.mod.help;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.HyperlinkEvent;
import javax.swing.tree.TreePath;

/**
 *
 * @author ShookTea
 */
public class HelpLibrary extends javax.swing.JInternalFrame {

    /** Creates new form HelpLibrary */
    public HelpLibrary() {
        initComponents();
        initFiles();
    }
    
    private void initFiles() {
        pathes.put("Podstawy korzystania z programu", "podstawy");
        pathes.put("Aktualizacje", "update");
        pathes.put("Czy masz jakiś problem?", "issue");
        pathes.put("Moduł Finanse", "/fin/index");
        pathes.put("Moduł Finanse::Tworzenie nowego miesiąca", "/fin/miesiac");
        pathes.put("Moduł Finanse::Tworzenie i usuwanie wpisów", "/fin/wpis");
        pathes.put("Moduł Finanse::Zamykanie miesiąca", "/fin/zamykanie");
        pathes.put("Moduł Finanse::Podsumowanie roku", "/fin/rok");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pomoc programu");

        jSplitPane1.setDividerLocation(160);

        panel.setEditable(false);
        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setContentType("text/html"); // NOI18N
        panel.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                panelHyperlinkUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(panel);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Pomoc programu");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Podstawy korzystania z programu");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Aktualizacje");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Czy masz jakiś problem?");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Moduł Finanse");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Tworzenie nowego miesiąca");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Tworzenie i usuwanie wpisów");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Zamykanie miesiąca");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Podsumowanie roku");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        TreePath path = evt.getPath();
        ArrayList<String> a = new ArrayList();
        while (path != null) {
            a.add(path.getLastPathComponent().toString());
            path = path.getParentPath();
        }
        String b = "";
        for (int i = a.size() - 2; i >= 0; i--) {
            if (!b.isEmpty()) {
                b += "::";
            }
            b += a.get(i);
            b = b.trim();
        }
        
        if (pathes.containsKey(b)) {
            String p = "/st/finanse/mod/help/" + pathes.get(b) + ".html";
            load(p);
        }
    }//GEN-LAST:event_treeValueChanged

    private void panelHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_panelHyperlinkUpdate
        try {
            if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                Desktop.getDesktop().browse(evt.getURL().toURI());
            }
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(HelpLibrary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_panelHyperlinkUpdate

    private final HashMap<String, String> pathes = new HashMap();
    
    private void load(String path) {
        Scanner sc = new Scanner(HelpLibrary.class.getResourceAsStream(path));
        String code = "";
        while (sc.hasNextLine()) {
            code += sc.nextLine();
        }
        String res = getClass().getResource("/st/finanse/mod/help/img/updateSearch.jpg").toString().replace("/st/finanse/mod/help/img/updateSearch.jpg", "");
        code = code.replace("<img src=\"", "<img src=\"" + res);
        sc.close();
        panel.setText(code);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JEditorPane panel;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

}
