package st.finanse.mod.chart;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import st.finanse.UpdateI;
import st.finanse.mod.finance.Finance;

/**
 *
 * @author ShookTea
 */
public class ChartWindow extends javax.swing.JInternalFrame implements UpdateI {

    /** Creates new form FinanceChart */
    public ChartWindow(Chart c) {
        this.c = c;
        initComponents();
    }
    
    private final Chart c;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new st.finanse.mod.chart.ChartPanel(c);

        setClosable(true);
        setIconifiable(true);
        setTitle("Wykres miesiąca");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private st.finanse.mod.chart.ChartPanel panel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateData() {
        c.update();
        this.repaint();
        panel.repaint();
    }
}
